# Generated by Django 3.1.2 on 2020-10-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imggal',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='image_gallery.location'),
        ),
        migrations.AlterField(
            model_name='imggal',
            name='imgdesc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='imggal',
            name='imgtitle',
            field=models.CharField(max_length=50),
        ),
    ]
